---
final_name: kafka-example-service-adapter
blobstore:
  provider: s3
  options:
    bucket_name: kafka-example-service-adapter-release-bosh-blobs
    region: eu-west-1
    endpoint: https://s3-eu-west-1.amazonaws.com
